components:
  schemas:
    UsersProfileInfoRequest:
      type: object
      additionalProperties: false
      properties:
        username:
          type: string
        password:
          type: string
        email:
          type: string
      required:
      - username
      - password
      - email

    UsersProfileInfoResponse:
      type: object
      additionalProperties: false
      properties:
        name:
          type: string
        surname:
          type: string
        birthdate:
          type: string
        phone:
          type: string
        bio:
          type: string
    required:
    - name
    - surname
    - birthdate
    - phone
    - bio
