components:
  schemas:
    UsersSignupRequest:
      type: object
      additionalProperties: false
      properties:
        username:
          type: string
        password:
          type: string
      required:
      - username
      - password

    UsersSignupResponse:
      type: object
      additionalProperties: false
      properties:
        message:
          type: string
      required:
      - message
