version: '3'

services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "8000:8000"
    depends_on:
      - users-service
      - posts-service
    networks:
      - app-network

  users-service:
    build: ./users-service
    depends_on:
      - users_db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@users_db:5432/users
    networks:
      - app-network
  
  posts_service:
    build: .
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@posts_db:5432/posts
      - GRPC_PORT=50051
    depends_on:
      - posts_db
    networks:
      - app-network

  posts_db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=posts
    volumes:
      - postgres_data:/var/lib/postgresql/data

  users_db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=users
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:

volumes:
  postgres_data:
