version: '3'

services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "8000:8000"
    depends_on:
      - users-service
      - posts-service
    networks:
      - app-network
      - posts-network
      - users-network

  users-service:
    build: ./users-service
    depends_on:
      - users_db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@users_db:5432/users
    networks:
      - app-network
      - users-network
  
  users_db:
    image: postgres:13
    volumes:
      - users_postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=users
    ports:
      - "5432:5432"
    networks:
      - users-network
  
  posts_db:
    image: postgres:latest
    container_name: postservice_postgres
    environment:
      POSTGRES_USER: postservice
      POSTGRES_PASSWORD: postservicepass
      POSTGRES_DB: postservicedb
    volumes:
      - posts_postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - app-network
      - posts-network

  posts-service:
    build: ./posts-service
    depends_on:
      - posts_db
    environment:
      - DATABASE_USER=postservice
      - DATABASE_PASSWORD=postservicepass
      - DATABASE_HOST=posts_db
      - DATABASE_PORT=5432
      - DATABASE_NAME=postservicedb
      - GRPC_HOST=0.0.0.0
      - GRPC_PORT=50051
    ports:
      - "50051:50051"
    networks:
      - app-network
      - posts-network

networks:
  app-network:
  posts-network:
  users-network:

volumes:
  users_postgres_data:
  posts_postgres_data:
